# Generated by Django 3.2 on 2021-04-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/our_team/')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('fb', models.CharField(max_length=200)),
                ('lin', models.CharField(max_length=200)),
                ('git', models.CharField(max_length=200)),
                ('tw', models.CharField(max_length=200)),
            ],
        ),
    ]
