# Generated by Django 3.2 on 2021-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0003_our_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/logo/')),
            ],
        ),
    ]
