# Generated by Django 3.2 on 2021-04-23 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0004_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 23, 34, 16, 388521)),
        ),
    ]
