# Generated by Django 3.2 on 2021-04-24 17:08

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0005_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 23, 8, 51, 200633)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
