# Generated by Django 3.2 on 2021-04-25 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0007_auto_20210425_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 15, 50, 56, 254485)),
        ),
    ]
