# Generated by Django 3.2 on 2021-04-25 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0008_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 23, 53, 21, 560421)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='mail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
