# Generated by Django 3.2 on 2021-04-25 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web_english', '0009_auto_20210425_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUpdate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('image', models.ImageField(default='static/propic/pro_avter.png', upload_to='static/profile/')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 3, 13, 43, 481415)),
        ),
    ]
