# Generated by Django 3.2 on 2021-04-25 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0010_auto_20210426_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 4, 10, 10, 70453)),
        ),
    ]
