# Generated by Django 3.2 on 2021-04-27 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0014_auto_20210427_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='android_stor',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='android_stor',
            name='app_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='android_stor',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='android_stor',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='android_stor',
            name='titel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 15, 26, 8, 114377)),
        ),
    ]
