# Generated by Django 3.2 on 2021-04-29 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0017_auto_20210427_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 14, 29, 32, 884307)),
        ),
    ]
