# Generated by Django 3.2 on 2021-04-29 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0021_auto_20210430_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_titel',
            name='slide_image',
            field=models.ImageField(default='', upload_to='static/slide_image/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 1, 42, 21, 178610)),
        ),
        migrations.AlterField(
            model_name='head_titel',
            name='button_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='head_titel',
            name='subtitel',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='head_titel',
            name='titel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
