# Generated by Django 3.2 on 2021-04-30 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0022_auto_20210430_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('subtitel', models.CharField(max_length=100)),
                ('subtitle2', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='static/content/')),
                ('image2', models.ImageField(upload_to='static/content/')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 23, 4, 48, 542715)),
        ),
    ]
