# Generated by Django 3.2 on 2021-04-30 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0025_auto_20210430_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_1',
            name='name1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='content_1',
            name='name2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='content_1',
            name='positons',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='content_2',
            name='name1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='content_2',
            name='name2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='content_2',
            name='positons',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 23, 50, 48, 78217)),
        ),
    ]
