# Generated by Django 3.2 on 2021-05-05 18:52

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0028_alter_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Android_storAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='', max_length=50)),
                ('app_category', models.CharField(default='', max_length=50)),
                ('body', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='static/android_stor/')),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='App_CategoryAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AppListAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lists', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/blog_image/')),
                ('post', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 6, 0, 52, 43, 829166))),
            ],
        ),
        migrations.CreateModel(
            name='Brand_logoAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/logo/')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content_1AR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='', max_length=100)),
                ('subtitel', models.CharField(default='', max_length=100)),
                ('subtitle2', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='static/content/')),
                ('image2', models.ImageField(default='', upload_to='static/content/')),
                ('positons', models.CharField(default='', max_length=50)),
                ('name1', models.CharField(default='', max_length=50)),
                ('name2', models.CharField(default='', max_length=50)),
                ('button_url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Content_2AR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='', max_length=100)),
                ('subtitel', models.CharField(default='', max_length=100)),
                ('subtitle2', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='static/content/')),
                ('image2', models.ImageField(default='', upload_to='static/content/')),
                ('positons', models.CharField(default='', max_length=50)),
                ('name1', models.CharField(default='', max_length=50)),
                ('name2', models.CharField(default='', max_length=50)),
                ('button_url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_body', models.TextField()),
                ('thumbnail', models.ImageField(default='', upload_to='static/course_pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Head_titelAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='', max_length=50)),
                ('subtitel', models.CharField(default='', max_length=200)),
                ('button_link', models.CharField(default='', max_length=200)),
                ('slide_image', models.ImageField(default='', upload_to='static/slide_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Our_teamAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/our_team/')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('fb', models.CharField(max_length=200)),
                ('lin', models.CharField(max_length=200)),
                ('git', models.CharField(max_length=200)),
                ('tw', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 0, 52, 43, 821355)),
        ),
    ]
