# Generated by Django 3.2 on 2021-05-16 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0029_auto_20210506_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Android_storAR',
        ),
        migrations.DeleteModel(
            name='App_CategoryAR',
        ),
        migrations.DeleteModel(
            name='AppListAR',
        ),
        migrations.DeleteModel(
            name='BlogAR',
        ),
        migrations.DeleteModel(
            name='Brand_logoAR',
        ),
        migrations.DeleteModel(
            name='CategoryAR',
        ),
        migrations.DeleteModel(
            name='Content_1AR',
        ),
        migrations.DeleteModel(
            name='Content_2AR',
        ),
        migrations.DeleteModel(
            name='CourseAR',
        ),
        migrations.DeleteModel(
            name='Head_titelAR',
        ),
        migrations.DeleteModel(
            name='Our_teamAR',
        ),
        migrations.DeleteModel(
            name='SubscriptionAR',
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(default='', upload_to='static/course_pic/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 15, 16, 6, 447945)),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
