(function(g){var window=this;'use strict';var aKa=function(a,b){return g.Mb(a,b)},D4=function(a,b,c){a.l.set(b,c)},E4=function(a){D4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ra()).toString(36));
return a},F4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.cn(a.l,b,c)},bKa=function(a,b){var c=[];
g.$i(b,function(d){try{var e=g.Sn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Rn(e)&&c.push(d)},a);
return c},cKa=function(a,b){b=bKa(a,b);
g.zb(b,function(c){g.Sn.prototype.remove.call(this,c)},a)},dKa=function(a){if(a.V){if(a.V.locationOverrideToken)return{locationOverrideToken:a.V.locationOverrideToken};
if(null!=a.V.latitudeE7&&null!=a.V.longitudeE7)return{latitudeE7:a.V.latitudeE7,longitudeE7:a.V.longitudeE7}}return null},eKa=function(a,b){g.fb(a,b)||a.push(b)},G4=function(a){var b=0,c;
for(c in a)b++;return b},fKa=function(a,b){b=b instanceof g.Bc?b:g.Ic(b,/^data:image\//i.test(b));
a.src=g.Cc(b)},gKa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},hKa=function(a){if(a.Ag&&"function"==typeof a.Ag)return a.Ag();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Jb(a)},iKa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)g.zb(a,b,void 0);else{if(a.wh&&"function"==typeof a.wh)var c=a.wh();else if(a.Ag&&"function"==typeof a.Ag)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Kb(a);d=hKa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},jKa=function(a,b,c,d){var e=new g.Rm(null,void 0);
a&&g.Sm(e,a);b&&g.Tm(e,b);c&&g.Um(e,c);d&&(e.J=d);return e},H4=function(){},I4=function(a,b){g.Iq[a]=!0;
var c=g.Gq();c&&c.publish.apply(c,arguments);g.Iq[a]=!1},J4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Om;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",kKa(this,a.capabilities||""),lKa(this,a.experiments||""))},kKa=function(a,b){a.capabilities.clear();
g.Le(b.split(","),g.Pa(aKa,mKa)).forEach(function(c){a.capabilities.add(c)})},lKa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},K4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},L4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},nKa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},oKa=function(a){return new K4(a)},pKa=function(a){return Array.isArray(a)?g.Nc(a,oKa):[]},M4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},N4=function(a){return Array.isArray(a)?"["+g.Nc(a,M4).join(",")+"]":"null"},O4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},qKa=function(a){return g.Nc(a,function(b){return{key:b.id,
name:b.name}})},P4=function(a,b){return g.bb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},Q4=function(a,b){return g.bb(a,function(c){return L4(c,b)})},rKa=function(){var a=(0,g.Tu)();
a&&cKa(a,a.i.qk(!0))},R4=function(){var a=g.Wu("yt-remote-connected-devices")||[];
g.wb(a);return a},sKa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Nc(a,function(d,e){return 0==e?d:d.substring(c.length)})},tKa=function(a){g.Vu("yt-remote-connected-devices",a,86400)},T4=function(){if(S4)return S4;
var a=g.Wu("yt-remote-device-id");a||(a=O4(),g.Vu("yt-remote-device-id",a,31536E3));for(var b=R4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return S4=d},U4=function(){var a=R4(),b=T4();
g.fb(a,b);g.Zu()&&g.yb(a,b);a=sKa(a);if(g.gb(a))try{g.xo("remote_sid")}catch(c){}else try{g.vo("remote_sid",a.join(","),-1)}catch(c){}},uKa=function(){return g.Wu("yt-remote-session-browser-channel")},vKa=function(){return g.Wu("yt-remote-local-screens")||[]},wKa=function(){g.Vu("yt-remote-lounge-token-expiration",!0,86400)},xKa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Nc(vKa(),function(d){return d.loungeToken}),c=g.Nc(a,function(d){return d.loungeToken});
g.fh(c,function(d){return!g.fb(b,d)})&&wKa();
g.Vu("yt-remote-local-screens",a,31536E3)},yKa=function(a,b){g.Vu("yt-remote-session-browser-channel",a);
g.Vu("yt-remote-session-screen-id",b);a=R4();b=T4();g.fb(a,b)||a.push(b);tKa(a);U4()},V4=function(a){a||(g.Yu("yt-remote-session-screen-id"),g.Yu("yt-remote-session-video-id"));
U4();a=R4();g.kb(a,T4());tKa(a)},zKa=function(){if(!W4){var a=g.bo();
a&&(W4=new g.Mn(a))}},AKa=function(){zKa();
return W4?!!W4.get("yt-remote-use-staging-server"):!1},X4=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},BKa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},CKa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Y4=function(a){a.length?DKa(a.shift(),function(){Y4(a)}):Z4()},EKa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},DKa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.id(d,g.hg(a));(document.head||document.documentElement).appendChild(d)},FKa=function(){var a=X4(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},Z4=function(){var a=CKa();
a&&a(!1,"No cast extension found")},$4=function(){if(GKa){var a=2,b=CKa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;DKa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Z4,c)}},HKa=function(){$4();
var a=FKa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");Y4(a)},JKa=function(){$4();
var a=FKa();a.push.apply(a,g.ma(IKa.map(EKa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");Y4(a)},a5=function(a,b,c){g.F.call(this);
this.G=null!=c?(0,g.C)(a,c):a;this.Ff=b;this.C=(0,g.C)(this.NL,this);this.i=!1;this.l=0;this.u=this.yb=null;this.B=[]},b5=function(a,b,c){g.F.call(this);
this.B=null!=c?a.bind(c):a;this.Ff=b;this.u=null;this.i=!1;this.l=0;this.yb=null},c5=function(a){a.yb=g.Mm(function(){a.yb=null;
a.i&&!a.l&&(a.i=!1,c5(a))},a.Ff);
var b=a.u;a.u=null;a.B.apply(null,b)},d5=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return gKa(a)},e5=function(){},f5=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},h5=function(a){g5.dispatchEvent(new KKa(g5,a))},KKa=function(a,b){g.Il.call(this,"statevent",a);
this.stat=b},i5=function(){},LKa=function(){},NKa=function(a){return(a=MKa(a))?new ActiveXObject(a):new XMLHttpRequest},MKa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},j5=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.S_(this);this.u=new g.Lm;this.u.setInterval(250)},PKa=function(a,b,c){a.Mq=1;
a.Cl=E4(b.clone());a.Io=c;a.G=!0;OKa(a,null)},k5=function(a,b,c,d,e){a.Mq=1;
a.Cl=E4(b.clone());a.Io=null;a.G=c;e&&(a.VI=!1);OKa(a,d)},OKa=function(a,b){a.Dq=Date.now();
l5(a);a.Fm=a.Cl.clone();F4(a.Fm,"t",a.J);a.ju=0;a.He=a.i.Az(a.i.Kt()?b:null);0<a.Ey&&(a.Rw=new b5((0,g.C)(a.LJ,a,a.He),a.Ey));a.B.Na(a.He,"readystatechange",a.bS);b=a.Tm?g.Tb(a.Tm):{};a.Io?(a.Hx="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.He.send(a.Fm,a.Hx,a.Io,b)):(a.Hx="GET",a.VI&&!g.Be&&(b.Connection="close"),a.He.send(a.Fm,a.Hx,null,b));a.i.Gi(1)},SKa=function(a,b,c){for(var d=!0;!a.Bn&&a.ju<c.length;){var e=QKa(a,c);
if(e==m5){4==b&&(a.xl=4,h5(15),d=!1);break}else if(e==RKa){a.xl=4;h5(16);d=!1;break}else n5(a,e)}4==b&&0==c.length&&(a.xl=1,h5(17),d=!1);a.Qi=a.Qi&&d;d||(o5(a),p5(a))},QKa=function(a,b){var c=a.ju,d=b.indexOf("\n",c);
if(-1==d)return m5;c=Number(b.substring(c,d));if(isNaN(c))return RKa;d+=1;if(d+c>b.length)return m5;b=b.substr(d,c);a.ju=d+c;return b},UKa=function(a,b){a.Dq=Date.now();
l5(a);var c=b?window.location.hostname:"";a.Fm=a.Cl.clone();D4(a.Fm,"DOMAIN",c);D4(a.Fm,"t",a.J);try{a.Ti=new ActiveXObject("htmlfile")}catch(m){o5(a);a.xl=7;h5(22);p5(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in q5)f=q5[f];else if(f in TKa)f=q5[f]=TKa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
q5[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ed(g.dc("b/12014412"),d+"</body></html>");a.Ti.open();a.Ti.write(g.ad(c));a.Ti.close();a.Ti.parentWindow.m=(0,g.C)(a.zR,a);a.Ti.parentWindow.d=(0,g.C)(a.hI,a,!0);a.Ti.parentWindow.rpcClose=(0,g.C)(a.hI,a,!1);c=a.Ti.createElement("DIV");a.Ti.parentWindow.document.body.appendChild(c);d=g.Hc(a.Fm.toString());d=g.pd(g.Cc(d));d=g.ed(g.dc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.fd(c,d);a.i.Gi(1)},l5=function(a){a.LC=Date.now()+
a.C;
VKa(a,a.C)},VKa=function(a,b){if(null!=a.Rq)throw Error("WatchDog timer not null");
a.Rq=f5((0,g.C)(a.HR,a),b)},r5=function(a){a.Rq&&(g.A.clearTimeout(a.Rq),a.Rq=null)},p5=function(a){a.i.LD()||a.Bn||a.i.Cu(a)},o5=function(a){r5(a);
g.Ci(a.Rw);a.Rw=null;a.u.stop();g.MEa(a.B);if(a.He){var b=a.He;a.He=null;b.abort();b.dispose()}a.Ti&&(a.Ti=null)},n5=function(a,b){try{a.i.ZH(a,b),a.i.Gi(4)}catch(c){}},XKa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;WKa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){XKa(a,b,c,d,f)},f)})}},WKa=function(a,b,c){var d=new Image;
d.onload=function(){try{s5(d),c(!0)}catch(e){}};
d.onerror=function(){try{s5(d),c(!1)}catch(e){}};
d.onabort=function(){try{s5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{s5(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
fKa(d,a)},s5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},t5=function(a){g.bm.call(this);
this.headers=new g.Om;this.ra=a||null;this.B=!1;this.ma=this.i=null;this.Fa=this.V="";this.G=0;this.u="";this.C=this.Ba=this.L=this.xa=!1;this.J=0;this.X=null;this.Ka="";this.Y=this.Ea=!1},YKa=function(a){return g.ze&&g.be(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},ZKa=function(a){return"content-type"==a.toLowerCase()},aLa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.G=5;$Ka(a);u5(a)},$Ka=function(a){a.xa||(a.xa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},cLa=function(a){if(a.B&&"undefined"!=typeof g.W_)if(a.ma[1]&&4==v5(a)&&2==a.getStatus())w5(a,"Local request error detected and ignored");
else if(a.L&&4==v5(a))g.Mm(a.WH,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){w5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.zd(1,String(a.V));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!bLa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.G=6;try{var l=2<v5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";$Ka(a)}}finally{u5(a)}}},u5=function(a,b){if(a.i){dLa(a);
var c=a.i,d=a.ma[0]?g.Ia:null;a.i=null;a.ma=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},dLa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},v5=function(a){return a.i?a.i.readyState:0},x5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},w5=function(a,b){return b+" ["+a.Fa+" "+a.V+" "+a.getStatus()+"]"},eLa=function(a){this.i=a;
this.l=new e5},fLa=function(a){var b=y5(a.i,a.Hr,"/mail/images/cleardot.gif");
E4(b);XKa(b.toString(),5E3,(0,g.C)(a.IM,a),3,2E3);a.Gi(1)},A5=function(a){var b=a.i.L;
if(null!=b)h5(5),b?(h5(11),z5(a.i,a,!1)):(h5(12),z5(a.i,a,!0));else if(a.Jg=new j5(a,void 0,void 0,void 0),a.Jg.Tm=a.Fy,b=a.i,b=y5(b,b.Kt()?a.wr:null,a.Gy),h5(5),!g.ze||g.ce(10))F4(b,"TYPE","xmlhttp"),k5(a.Jg,b,!1,a.wr,!1);else{F4(b,"TYPE","html");var c=a.Jg;a=!!a.wr;c.Mq=3;c.Cl=E4(b.clone());UKa(c,a)}},B5=function(a,b,c){this.eb=1;
this.i=[];this.u=[];this.B=new e5;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},gLa=function(a,b){this.i=a;
this.map=b;this.context=null},hLa=function(a,b,c,d){g.Il.call(this,"timingevent",a);
this.size=b;this.Dt=d},iLa=function(a){g.Il.call(this,"serverreachability",a)},lLa=function(a){jLa(a);
if(3==a.eb){var b=a.Vs++,c=a.ev.clone();D4(c,"SID",a.l);D4(c,"RID",b);D4(c,"TYPE","terminate");C5(a,c);b=new j5(a,a.l,b,void 0);b.Mq=2;b.Cl=E4(c.clone());fKa(new Image,b.Cl.toString());b.Dq=Date.now();l5(b)}kLa(a)},mLa=function(a){a.fN(1,0);
a.ev=y5(a,null,a.Hy);D5(a)},jLa=function(a){a.Hl&&(a.Hl.abort(),a.Hl=null);
a.Ud&&(a.Ud.cancel(),a.Ud=null);a.vk&&(g.A.clearTimeout(a.vk),a.vk=null);E5(a);a.yg&&(a.yg.cancel(),a.yg=null);a.Pl&&(g.A.clearTimeout(a.Pl),a.Pl=null)},nLa=function(a,b){if(0==a.eb)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new gLa(a.CO++,b));2!=a.eb&&3!=a.eb||D5(a)},oLa=function(a){var b=0;
a.Ud&&b++;a.yg&&b++;return b},D5=function(a){a.yg||a.Pl||(a.Pl=f5((0,g.C)(a.fI,a),0),a.Up=0)},qLa=function(a,b){if(1==a.eb){if(!b){a.Vs=Math.floor(1E5*Math.random());
b=a.Vs++;var c=new j5(a,"",b,void 0);c.Tm=a.mj;var d=F5(a),e=a.ev.clone();D4(e,"RID",b);D4(e,"CVER","1");C5(a,e);PKa(c,e,d);a.yg=c;a.eb=2}}else 3==a.eb&&(b?pLa(a,b):0==a.i.length||a.yg||pLa(a))},pLa=function(a,b){if(b)if(6<a.Cn){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Vs-1;b=F5(a)}else c=b.L,b=b.Io;else c=a.Vs++,b=F5(a);var d=a.ev.clone();D4(d,"SID",a.l);D4(d,"RID",c);D4(d,"AID",a.nq);C5(a,d);c=new j5(a,a.l,c,a.Up+1);c.Tm=a.mj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yg=c;PKa(c,d,b)},C5=function(a,b){a.yf&&(a=a.yf.GF())&&g.Bb(a,function(c,d){D4(b,d,c)})},F5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Cn&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={hp:e.hp},f++){e.hp=a.i[f].i;var h=a.i[f].map;e.hp=6>=a.Cn?f:e.hp-d;try{g.Bb(h,function(l){return function(m,n){c.push("req"+l.hp+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.hp+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},rLa=function(a){a.Ud||a.vk||(a.G=1,a.vk=f5((0,g.C)(a.eI,a),0),a.Jp=0)},G5=function(a){if(a.Ud||a.vk||3<=a.Jp)return!1;
a.G++;a.vk=f5((0,g.C)(a.eI,a),sLa(a,a.Jp));a.Jp++;return!0},z5=function(a,b,c){a.Fx=c;
a.nj=b.dk;a.C||mLa(a)},E5=function(a){null!=a.Jn&&(g.A.clearTimeout(a.Jn),a.Jn=null)},sLa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},H5=function(a,b){if(2==b||9==b){var c=null;
a.yf&&(c=null);var d=(0,g.C)(a.ES,a);c||(c=new g.Rm("//www.google.com/images/cleardot.gif"),E4(c));WKa(c.toString(),1E4,d)}else h5(2);tLa(a,b)},tLa=function(a,b){a.eb=0;
a.yf&&a.yf.XE(b);kLa(a);jLa(a)},kLa=function(a){a.eb=0;
a.nj=-1;if(a.yf)if(0==a.u.length&&0==a.i.length)a.yf.kz();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.yf.kz(b)}},y5=function(a,b,c){var d=g.Zm(c);
if(""!=d.i)b&&g.Tm(d,b+"."+d.i),g.Um(d,d.u);else{var e=window.location;d=jKa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Xr&&g.Bb(a.Xr,function(f,h){D4(d,h,f)});
D4(d,"VER",a.Cn);C5(a,d);return d},uLa=function(){},vLa=function(){this.i=[];
this.l=[]},wLa=function(a,b){this.action=a;
this.params=b||{}},I5=function(a,b){g.F.call(this);
this.i=new g.I(this.rR,0,this);g.G(this,this.i);this.Ff=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},J5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ma=a;this.G=b;this.u=new g.Ln;this.l=new I5(this.lS,this);this.i=null;this.X=!1;this.C=null;this.V="";this.L=this.B=0;this.J=[];this.ra=c;this.Y=d;this.xa=e},xLa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Fx,sessionId:a.i.l,arrayId:a.i.nq}},yLa=function(a,b){a.L=b||0;
a.l.stop();K5(a);a.i&&(3==a.i.getState()&&qLa(a.i),lLa(a.i));a.L=0},L5=function(a){return!!a.i&&3==a.i.getState()},K5=function(a){if(a.i){var b=a.Y(),c=a.i.mj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.mj=c}},M5=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.zd(4,a))||"";b&&(this.port=":"+b);this.domain=g.Ad(a)||"";a=g.Tc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zc(a,"10.0")&&(this.l=!1))},N5=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.Md(c+b,{})},O5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.B,d,!0),onError:g.Pa(a.u,e),onTimeout:g.Pa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.mp(b,a)},CLa=function(){var a=zLa;
ALa();P5.push(a);BLa()},Q5=function(a,b){ALa();
var c=DLa(a,String(b));g.gb(P5)?ELa(c):(BLa(),g.zb(P5,function(d){d(c)}))},ALa=function(){P5||(P5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",P5,void 0))},ELa=function(a){var b=(R5+1)%50;
R5=b;S5[b]=a;T5||(T5=49==b)},BLa=function(){var a=P5;
if(S5[0]){var b=T5?R5:-1;do{b=(b+1)%50;var c=S5[b];g.zb(a,function(d){d(c)})}while(b!=R5);
S5=Array(50);R5=-1;T5=!1}},DLa=function(a,b){var c=(Date.now()-FLa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},U5=function(a){g.O.call(this);
this.G=a;this.screens=[]},GLa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},HLa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Le(a.screens,function(f){return!!P4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=GLa(a,b[d])||c;return c},ILa=function(a,b){var c=a.screens.length;
a.screens=g.Le(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},V5=function(a,b,c,d,e){g.O.call(this);
this.u=a;this.J=b;this.B=c;this.G=d;this.C=e;this.l=0;this.i=null;this.yb=NaN},X5=function(a){U5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;W5(this);this.info("Initializing with "+N4(this.screens))},JLa=function(a){if(a.screens.length){var b=g.Nc(a.screens,function(d){return d.id}),c=N5(a.l,"/pairing/get_lounge_token_batch");
O5(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.CN,a),(0,g.C)(a.BN,a))}},W5=function(a){if(g.Go("deprecate_pair_servlet_enabled"))return HLa(a,[]);
var b=pKa(vKa());b=g.Le(b,function(c){return!c.uuid});
return HLa(a,b)},Y5=function(a,b){xKa(g.Nc(a.screens,nKa));
b&&wKa()},$5=function(a,b){g.O.call(this);
this.G=b;b=(b=g.Wu("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.G(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.fb(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;Z5("Initialized with "+g.Hj(this.i))},a6=function(a,b,c){var d=N5(a.C,"/pairing/get_screen_availability");
O5(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},b6=function(a,b){a:if(G4(b)!=G4(a.i))var c=!1;
else{c=g.Kb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(Z5("Updated online screens: "+g.Hj(a.i)),a.i=b,a.W("screenChange"));KLa(a)},c6=function(a){isNaN(a.u)||g.hp(a.u);
a.u=g.fp((0,g.C)(a.KB,a),0<a.B&&a.B<g.Ra()?2E4:1E4)},Z5=function(a){Q5("OnlineScreenService",a)},LLa=function(a){var b={};
g.zb(a.G(),function(c){c.token?b[c.token]=c.id:this.Hd("Requesting availability of screen w/o lounge token.")});
return b},KLa=function(a){a=g.Kb(g.Cb(a.i,function(b){return b}));
g.wb(a);a.length?g.Vu("yt-remote-online-screen-ids",a.join(","),60):g.Yu("yt-remote-online-screen-ids")},d6=function(a,b){b=void 0===b?!1:b;
U5.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};MLa(this)},OLa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Ug(),l=c?Q4(h,c):null;c&&(a.J||l)||(l=Q4(h,b));if(l){l.uuid=b;var m=e6(a,l);a6(a.i,m,function(n){e(n?m:null)})}else c?NLa(a,c,(0,g.C)(function(n){var p=e6(this,new K4({name:d,
screenId:c,loungeToken:n,dialId:b||""}));a6(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},PLa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},QLa=function(a,b,c){a6(a.i,b,c)},NLa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.mp(N5(a.B,"/pairing/get_lounge_token_batch"),e)},RLa=function(a){a.screens=a.l.Ug();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+N4(a.screens))},MLa=function(a){f6(a);
a.l=new X5(a.B);a.l.subscribe("screenChange",(0,g.C)(a.IN,a));RLa(a);a.J||(a.u=pKa(g.Wu("yt-remote-automatic-screen-cache")||[]));f6(a);a.info("Initializing automatic screens: "+N4(a.u));a.i=new $5(a.B,(0,g.C)(a.Ug,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.W("onlineScreenChange")},a))},e6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Q4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||SLa(a));f6(a);a.C[b.uuid]=b.id;g.Vu("yt-remote-device-id-map",a.C,31536E3);return b},SLa=function(a){a=g.Le(a.u,function(b){return"shortLived"!=b.idType});
g.Vu("yt-remote-automatic-screen-cache",g.Nc(a,nKa))},f6=function(a){a.C=g.Wu("yt-remote-device-id-map")||{}},g6=function(a,b,c){g.O.call(this);
this.xa=c;this.u=a;this.i=b;this.B=null},h6=function(a,b){a.B=b;
a.W("sessionScreen",a.B)},TLa=function(a,b){a.B&&(a.B.token=b,e6(a.u,a.B));
a.W("sessionScreen",a.B)},i6=function(a,b){Q5(a.xa,b)},j6=function(a,b,c){g6.call(this,a,b,"CastSession");
var d=this;this.Ba=c;this.l=null;this.Y=(0,g.C)(this.SL,this);this.ra=(0,g.C)(this.LR,this);this.X=g.fp(function(){ULa(d,null)},12E4);
this.J=this.C=this.G=this.L=0;this.ma=!1;this.V="unknown"},k6=function(a,b){g.hp(a.J);
a.J=0;0==b?VLa(a):a.J=g.fp(function(){VLa(a)},b)},VLa=function(a){WLa(a,"getLoungeToken");
g.hp(a.C);a.C=g.fp(function(){XLa(a,null)},3E4)},WLa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Hj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.C)(function(){i6(this,"Failed to send message: "+b+".")},a)):i6(a,"Sending yt message without session: "+g.Hj(c))},l6=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.VF(b,function(c){h6(a,c)},function(){return a.Zf()},5)):a.Zf(Error("Waiting for session status timed out."))},ZLa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new K4(b);YLa(a,d,function(e){e?(a.ma=!0,e6(a.u,d),h6(a,d),a.V="unknown",k6(a,c)):(g.Lo(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Zf())},5)},ULa=function(a,b){g.hp(a.X);
a.X=0;b?a.Ba.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?ZLa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Lo(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),l6(a,b.screenId))):(g.Lo(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
l6(a,b.screenId)):l6(a,b.screenId):a.Zf(Error("Waiting for session status timed out."))},XLa=function(a,b){g.hp(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.V=c,k6(a,3E4)):(TLa(a,b.loungeToken),a.ma=!1,a.V="unknown",k6(a,b.loungeTokenRefreshIntervalMs))},YLa=function(a,b,c,d){g.hp(a.G);
a.G=0;QLa(a.u,b,function(e){e||0>d?c(e):a.G=g.fp(function(){YLa(a,b,c,d-1)},300)})},$La=function(a){g.hp(a.L);
a.L=0;g.hp(a.G);a.G=0;g.hp(a.X);a.X=0;g.hp(a.C);a.C=0;g.hp(a.J);a.J=0},m6=function(a,b,c,d){g6.call(this,a,b,"DialSession");
this.Ea=d;this.l=this.L=null;this.ra="";this.Fa=c;this.Ca=null;this.X=g.Ia;this.V=NaN;this.Ba=(0,g.C)(this.TL,this);this.C=g.Ia;this.J=this.G=0;this.Y=!1;this.ma="unknown"},n6=function(a){var b;
return!!(a.Ea.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},aMa=function(a){a.C=a.u.ND(a.ra,a.i.label,a.i.friendlyName,n6(a),function(b,c){a.C=g.Ia;
a.Y=!0;h6(a,b);"shortLived"==b.idType&&0<c&&o6(a,c)},function(b){a.C=g.Ia;
a.Zf(b)})},bMa=function(a){var b={};
b.pairingCode=a.ra;b.theme=a.Fa;AKa()&&(b.env_useStageMdx=1);return g.Jd(b)},p6=function(a){return new Promise(function(b){a.ra=O4();
if(a.Ca){var c=new chrome.cast.DialLaunchResponse(!0,bMa(a));b(c);aMa(a)}else a.X=function(){g.hp(a.V);a.X=function(){};
a.V=NaN;var d=new chrome.cast.DialLaunchResponse(!0,bMa(a));b(d);aMa(a)},a.V=g.fp(function(){a.X()},100)})},dMa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new K4(b);return(new Promise(function(e){cMa(a,d,function(f){f?(a.Y=!0,e6(a.u,d),h6(a,d),o6(a,c)):g.Lo(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):p6(a)})},eMa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){OLa(a.u,c,b,d,function(f){f&&f.token&&h6(a,f);e(f)},function(f){i6(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):p6(a)})},cMa=function(a,b,c,d){g.hp(a.G);
a.G=0;QLa(a.u,b,function(e){e||0>d?c(e):a.G=g.fp(function(){cMa(a,b,c,d-1)},300)})},o6=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
n6(a)&&(g.hp(a.J),a.J=0,0==b?fMa(a):a.J=g.fp(function(){fMa(a)},b))},fMa=function(a){n6(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ma=c,o6(a,3E4)):(a.Y=!1,a.ma="unknown",TLa(a,b.loungeToken),o6(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ma="noLoungeTokenResponse";o6(a,3E4)})},gMa=function(a){g.hp(a.G);
a.G=0;g.hp(a.J);a.J=0;a.C();a.C=function(){};
g.hp(a.V)},q6=function(a,b){g6.call(this,a,b,"ManualSession");
this.l=g.fp((0,g.C)(this.oq,this,null),150)},r6=function(a,b){g.O.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.V=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.G=(0,g.C)(this.HQ,this)},hMa=function(a,b){return b?g.bb(a.u,function(c){return L4(b,c.label)},a):null},s6=function(a){Q5("Controller",a)},zLa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},t6=function(a){return a.J||!!a.u.length||!!a.i},u6=function(a,b,c){b!=a.i&&(g.Ci(a.i),(a.i=b)?(c?a.W("yt-remote-cast2-receiver-resumed",
b.i):a.W("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.cI,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.oq(null)):a.W("yt-remote-cast2-session-change",null))},iMa=function(a){var b=a.l.MD(),c=a.i&&a.i.i;
a=g.Nc(b,function(d){c&&L4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=hMa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},nMa=function(a,b,c,d){d.disableCastApi?v6("Cannot initialize because disabled by Mdx config."):jMa()?kMa(b,d)&&(w6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?lMa(a,c):(window.__onGCastApiAvailable=function(e,f){e?lMa(a,c):(x6("Failed to load cast API: "+f),y6(!1),w6(!1),g.Yu("yt-remote-cast-available"),g.Yu("yt-remote-cast-receiver"),
mMa(),c(!1))},d.loadCastApiSetupScript?g.$u("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=X4()&&HKa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?Z4():89<=X4()?JKa():($4(),Y4(IKa.map(EKa))))):v6("Cannot initialize because not running Chrome")},mMa=function(){v6("dispose");
var a=z6();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);oMa(!1);g.Lq(A6);A6.length=0},B6=function(){return!!g.Wu("yt-remote-cast-installed")},pMa=function(){var a=g.Wu("yt-remote-cast-receiver");
return a?a.friendlyName:null},qMa=function(){v6("clearCurrentReceiver");
g.Yu("yt-remote-cast-receiver")},rMa=function(){return B6()?z6()?z6().getCastSession():(x6("getCastSelector: Cast is not initialized."),null):(x6("getCastSelector: Cast API is not installed!"),null)},D6=function(){B6()?z6()?C6()?(v6("Requesting cast selector."),z6().requestSession()):(v6("Wait for cast API to be ready to request the session."),A6.push(g.Kq("yt-remote-cast2-api-ready",D6))):x6("requestCastSelector: Cast is not initialized."):x6("requestCastSelector: Cast API is not installed!")},E6=
function(a,b){C6()?z6().setConnectedScreenStatus(a,b):x6("setConnectedScreenStatus called before ready.")},jMa=function(){var a=0<=g.Tc.search(/ (CrMo|Chrome|CriOS)\//);
return g.SA||a},sMa=function(a,b){z6().init(a,b)},kMa=function(a,b){var c=!1;
z6()||(a=new r6(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Vu("yt-remote-cast-available",d);I4("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){v6("onReceiverSelected: "+d.friendlyName);
g.Vu("yt-remote-cast-receiver",d);I4("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){v6("onReceiverResumed: "+d.friendlyName);
g.Vu("yt-remote-cast-receiver",d);I4("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){v6("onSessionChange: "+M4(d));
d||g.Yu("yt-remote-cast-receiver");I4("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
v6("cloudview.createSingleton_: "+c);return c},z6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},lMa=function(a,b){y6(!0);
w6(!1);sMa(a,function(c){c?(oMa(!0),g.Mq("yt-remote-cast2-api-ready")):(x6("Failed to initialize cast API."),y6(!1),g.Yu("yt-remote-cast-available"),g.Yu("yt-remote-cast-receiver"),mMa());b(c)})},v6=function(a){Q5("cloudview",a)},x6=function(a){Q5("cloudview",a)},y6=function(a){v6("setCastInstalled_ "+a);
g.Vu("yt-remote-cast-installed",a)},C6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},oMa=function(a){v6("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},w6=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},F6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.G=this.J=0;this.trackData=null;this.hasNext=this.Cj=!1;this.L=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},G6=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Cj=!1;a.hasNext=!1;a.J=0;a.G=g.Ra();a.B=0;a.i=0;a.C=0;a.L=0;a.u=NaN;a.l=!1},H6=function(a){return a.lc()?(g.Ra()-a.G)/1E3:0},I6=function(a,b){a.J=b;
a.G=g.Ra()},J6=function(a){switch(a.playerState){case 1:case 1081:return(g.Ra()-a.G)/1E3+a.J;
case -1E3:return 0}return a.J},K6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&G6(a)},L6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Ub(a.trackData);b.hasPrevious=a.Cj;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.G;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.L;b.liveIngestionTime=a.u;return b},N6=function(a,b){g.O.call(this);
this.eb=0;this.u=a;this.C=[];this.B=new vLa;this.l=this.i=null;this.L=(0,g.C)(this.kP,this);this.G=(0,g.C)(this.Ys,this);this.J=(0,g.C)(this.jP,this);this.V=(0,g.C)(this.rP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.WB,this),tMa(this))):c=3;0!=c&&(b?this.WB(c):g.fp((0,g.C)(function(){this.WB(c)},this),0));
(a=rMa())&&M6(this,a);this.subscribe("yt-remote-cast2-session-change",this.V)},O6=function(a){return new F6(a.u.getPlayerContextData())},tMa=function(a){g.zb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Pa(this.EQ,b),this))},a)},uMa=function(a){g.zb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},P6=function(a){return 1==a.getState()},Q6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},S6=function(a,b,c){var d=O6(a);
I6(d,c);-1E3!=d.playerState&&(d.playerState=b);R6(a,d)},T6=function(a,b,c){a.u.sendMessage(b,c)},R6=function(a,b){uMa(a);
a.u.setPlayerContextData(L6(b));tMa(a)},M6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.G),a.Ys(null));
a.l=b;a.l&&(Q5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.G),a.l.media.length&&a.Ys(a.l.media[0]))},vMa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=O6(a);b.contentId!=d.videoId&&Q5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;I6(d,a.i.getEstimatedTime());R6(a,d)}else Q5("CP","No cast media video. Ignoring state update.")},U6=function(a,b,c){return(0,g.C)(function(d){this.Hd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hd("Retrying "+b+" using MDx browser channel."),T6(this,b,c))},a)},V6=function(a,b,c){g.O.call(this);
this.C=NaN;this.ma=!1;this.L=this.J=this.X=this.Y=NaN;this.V=[];this.B=this.G=this.u=this.ac=this.i=null;this.xa=a;this.V.push(g.Lp(window,"beforeunload",(0,g.C)(this.yN,this)));this.l=[];this.ac=new F6;this.Ba=b.id;this.ra=b.idType;this.i=wMa(this,c);this.i.subscribe("handlerOpened",this.oP,this);this.i.subscribe("handlerClosed",this.lP,this);this.i.subscribe("handlerError",this.mP,this);this.i.subscribe("handlerMessage",this.nP,this);this.i.fx(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.ac.videoId;g.Zu()&&g.Vu("yt-remote-session-video-id",d)},this)},W6=function(a){Q5("conn",a)},wMa=function(a,b){return new J5(N5(a.xa,"/bc"),b,!1,function(){return a.RD()},"shortLived"==a.ra)},X6=function(a,b){a.W("proxyStateChange",b)},xMa=function(a){a.C=g.fp((0,g.C)(function(){W6("Connecting timeout");
this.Qp(1)},a),2E4)},Y6=function(a){g.hp(a.C);
a.C=NaN},Z6=function(a){g.hp(a.Y);
a.Y=NaN},yMa=function(a){$6(a);
a.X=g.fp((0,g.C)(function(){a7(this,"getNowPlaying")},a),2E4)},$6=function(a){g.hp(a.X);
a.X=NaN},AMa=function(a,b){b&&(Y6(a),Z6(a));
var c=L5(a.i)&&isNaN(a.C);b==c?b&&(X6(a,1),a7(a,"getSubtitlesTrack")):b?(a.UF()&&a.ac.reset(),X6(a,1),a7(a,"getNowPlaying"),zMa(a)):a.Qp(1)},BMa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ac.videoId&&(g.Pb(b.params)?a.ac.trackData=null:a.ac.trackData=b.params,a.W("remotePlayerChange"))},CMa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ac.listId=b.params.listId||a.ac.listId;K6(a.ac,c,d);a.W("remoteQueueChange")},EMa=function(a,b){b.params=b.params||{};
CMa(a,b);DMa(a,b);a.W("autoplayDismissed")},DMa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
I6(a.ac,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ac.playerState&&(c=-1E3);a.ac.playerState=c;c=Number(b.params.loadedTime);a.ac.L=isNaN(c)?0:c;c=Number(b.params.duration);a.ac.C=isNaN(c)?0:c;c=a.ac;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.ac;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.ac.playerState?yMa(a):$6(a);a.W("remotePlayerChange")},FMa=function(a,b){if(-1E3!=a.ac.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ac.playerState=c;b=parseInt(b.params.currentTime,10);I6(a.ac,isNaN(b)?0:b);a.W("remotePlayerChange")}},GMa=function(a,b){var c="true"==b.params.muted;
a.ac.volume=parseInt(b.params.volume,10);a.ac.muted=c;a.W("remotePlayerChange")},HMa=function(a,b){a.G=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},IMa=function(a,b){var c="true"==b.params.hasNext;
a.ac.Cj="true"==b.params.hasPrevious;a.ac.hasNext=c;a.W("previousNextChange")},zMa=function(a){g.hp(a.L);
a.L=g.fp((0,g.C)(a.Qp,a,1),864E5)},a7=function(a,b,c){c?W6("Sending: action="+b+", params="+g.Hj(c)):W6("Sending: action="+b);
a.i.sendMessage(b,c)},b7=function(a){U5.call(this,"ScreenServiceProxy");
this.Ef=a;this.i=[];this.i.push(this.Ef.$_s("screenChange",(0,g.C)(this.XL,this)));this.i.push(this.Ef.$_s("onlineScreenChange",(0,g.C)(this.lQ,this)))},MMa=function(a,b){zKa();
if(!W4||!W4.get("yt-remote-disable-remote-module-for-dev")){b=g.M("MDX_CONFIG")||b;rKa();U4();c7||(c7=new M5(b?b.loungeApiHost:void 0),AKa()&&(c7.i="/api/loungedev"));d7||(d7=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",d7,void 0));JMa();var c=e7();if(!c){var d=new d6(c7,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=e7();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});nMa(a,d,function(f){f?f7()&&E6(f7(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){I4("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),g7("Initializing: "+g.Hj(b)),h7.push(g.Kq("yt-remote-cast2-availability-change",function(){I4("yt-remote-receiver-availability-change")})),h7.push(g.Kq("yt-remote-cast2-receiver-selected",
function(){i7(null);
I4("yt-remote-auto-connect","cast-selector-receiver")})),h7.push(g.Kq("yt-remote-cast2-receiver-resumed",function(){I4("yt-remote-receiver-resumed","cast-selector-receiver")})),h7.push(g.Kq("yt-remote-cast2-session-change",KMa)),h7.push(g.Kq("yt-remote-connection-change",function(f){f?E6(f7(),"YouTube TV"):j7()||(E6(null,null),qMa())})),a=k7(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.Go("desktop_enable_autoplay")&&e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=
b.theme)&&(a.theme=b),g7(" -- with channel params: "+g.Hj(a)),a?(g.Vu("yt-remote-session-app",a.app),g.Vu("yt-remote-session-name",a.name)):(g.Yu("yt-remote-session-app"),g.Yu("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),f7()||LMa())}},NMa=function(){var a=e7().Ef.$_gos();
var b=l7();b&&m7()&&(P4(a,b)||a.push(b));return qKa(a)},n7=function(){var a=OMa();
!a&&B6()&&pMa()&&(a={key:"cast-selector-receiver",name:pMa()});return a},OMa=function(){var a=NMa(),b=l7();
b||(b=j7());return g.bb(a,function(c){return b&&L4(b,c.key)?!0:!1})},l7=function(){var a=f7();
if(!a)return null;var b=e7().Ug();return Q4(b,a)},KMa=function(a){g7("remote.onCastSessionChange_: "+M4(a));
if(a){var b=l7();if(b&&b.id==a.id){if(E6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))o7&&(o7.token=a),(b=m7())&&b.fx(a)}else b&&p7(),q7(a,1)}else m7()&&p7()},p7=function(){C6()?z6().stopSession():x6("stopSession called before API ready.");
var a=m7();a&&(a.disconnect(1),r7(null))},s7=function(){var a=m7();
return!!a&&3!=a.getProxyState()},g7=function(a){Q5("remote",a)},e7=function(){if(!t7){var a=g.Ha("yt.mdx.remote.screenService_");
t7=a?new b7(a):null}return t7},f7=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},PMa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},QMa=function(){return g.Ha("yt.mdx.remote.connectData_")},i7=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},m7=function(){return g.Ha("yt.mdx.remote.connection_")},r7=function(a){var b=m7();
i7(null);a||PMa("");g.Ga("yt.mdx.remote.connection_",a,void 0);d7&&(g.zb(d7,function(c){c(a)}),d7.length=0);
b&&!a?I4("yt-remote-connection-change",!1):!b&&a&&I4("yt-remote-connection-change",!0)},j7=function(){var a=g.Zu();
if(!a)return null;var b=e7();if(!b)return null;b=b.Ug();return Q4(b,a)},q7=function(a,b){f7();
l7()&&l7();u7?o7=a:(PMa(a.id),a=new V6(c7,a,k7()),a.connect(b,QMa()),a.subscribe("beforeDisconnect",function(c){I4("yt-remote-before-disconnect",c)}),a.subscribe("beforeDispose",function(){m7()&&(m7(),r7(null))}),a.subscribe("browserChannelAuthError",function(){var c=l7();
c&&"shortLived"==c.idType&&(C6()?z6().handleBrowserChannelAuthError():x6("refreshLoungeToken called before API ready."))}),r7(a))},LMa=function(){var a=j7();
a?(g7("Resume connection to: "+M4(a)),q7(a,0)):(V4(),qMa(),g7("Skipping connecting because no session screen found."))},JMa=function(){var a=k7();
if(g.Pb(a)){a=T4();var b=g.Wu("yt-remote-session-name")||"",c=g.Wu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},k7=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},v7=function(a,b,c){g.F.call(this);
var d=this;this.l=a;this.I=b;this.Pb=c;this.events=new g.VL(this);this.X=this.events.N(this.I,"onVolumeChange",function(e){RMa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.YI(64);this.i=new g.I(this.dJ,500,this);this.u=new g.I(this.eJ,1E3,this);this.L=new a5(this.WS,0,this);this.B={};this.V=new g.I(this.EJ,1E3,this);this.J=new b5(this.seekTo,1E3,this);this.Y=g.Ia;g.G(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.UP);this.events.N(b,"captionschanged",this.hP);this.events.N(b,"captionssettingschanged",this.jJ);this.events.N(b,"videoplayerreset",this.Jw);this.events.N(b,"mdxautoplaycancel",function(){d.Pb.qF()});
a=this.Pb;a.Ga();a.subscribe("proxyStateChange",this.YH,this);a.subscribe("remotePlayerChange",this.kt,this);a.subscribe("remoteQueueChange",this.Jw,this);a.subscribe("previousNextChange",this.VH,this);a.subscribe("nowAutoplaying",this.PH,this);a.subscribe("autoplayDismissed",this.mH,this);g.G(this,this.i);g.G(this,this.u);g.G(this,this.L);g.G(this,this.V);g.G(this,this.J);this.jJ();this.Jw();this.kt()},RMa=function(a,b){if(w7(a)){a.Pb.unsubscribe("remotePlayerChange",a.kt,a);
var c=Math.round(b.volume);b=!!b.muted;var d=O6(a.Pb);if(c!==d.volume||b!==d.muted)a.Pb.setVolume(c,b),a.V.start();a.Pb.subscribe("remotePlayerChange",a.kt,a)}},SMa=function(a){a.Tb(0);
a.i.stop();a.Hb(new g.YI(64))},x7=function(a,b){if(w7(a)&&!a.C){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.Wb(c,b));a.Pb.QD(a.I.getVideoData(1).videoId,c);a.B=O6(a.Pb).trackData}},y7=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Pb.playVideo(c.videoId,b,d,e,c.playerParams,c.xa,dKa(c));a.Hb(new g.YI(1))},TMa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{mG:1});
c&&c.length?(a.I.setOption("captions","track",b),a.C=!1):(a.I.loadModule("captions"),a.C=!0)}else a.I.setOption("captions","track",{})},w7=function(a){return O6(a.Pb).videoId===a.I.getVideoData(1).videoId},z7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",oa:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Da:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],oa:"Learn more"},{D:"button",Da:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],oa:"OK"}]}]}]});this.i=new g.EK(this,250);this.learnMoreButton=
this.Aa("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Aa("ytp-mdx-manual-pairing-popup-ok");g.G(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},A7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",oa:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",oa:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Da:["ytp-button","ytp-mdx-privacy-popup-cancel"],oa:"Cancel"},{D:"button",Da:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],oa:"Confirm"}]}]}]});this.i=new g.EK(this,250);this.cancelButton=this.Aa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Aa("ytp-mdx-privacy-popup-confirm");g.G(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},B7=function(a){g.V.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.Gma()]},{D:"div",K:"ytp-remote-display-status-text",oa:"{{statustext}}"}]}]});this.api=a;this.i=new g.EK(this,250);g.G(this,this.i);this.N(a,"presentingplayerstatechange",this.l);UMa(this,a.qb())},UMa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.BH("Error on $RECEIVER_NAME",c):b.lc()||g.U(b,4)?g.BH("Playing on $RECEIVER_NAME",c):g.BH("Connected to $RECEIVER_NAME",c);a.Oa("statustext",b);a.i.show()}else a.i.hide()},C7=function(a,b){g.OO.call(this,"Play on",0,a,b);
this.I=a;this.Cm={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},D7=function(a){g.cM.call(this,a);
this.Di={key:O4(),name:"This computer"};this.nh=null;this.subscriptions=[];this.yB=this.Pb=null;this.Cm=[this.Di];this.Jl=this.Di;this.Yc=new g.YI(64);this.HG=0;this.Oe=-1;this.tq=null;this.ut=this.hw=!1;this.Xk=this.Bq=null;if(!g.iD(this.player.T())&&!g.jD(this.player.T())){a=this.player;var b=g.IL(a);b&&(b=b.Yl())&&(b=new C7(a,b),g.G(this,b));b=new B7(a);g.G(this,b);g.SL(a,b.element,4);this.Bq=new A7;g.G(this,this.Bq);g.SL(a,this.Bq.element,4);g.R(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.R(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.tq=new z7,g.G(this,this.tq),g.SL(a,this.tq.element,4));this.ut=!!j7();this.hw=!!g.Wu("yt-remote-manual-pairing-warning-shown")}},E7=function(a){a.Xk&&(a.player.removeEventListener("presentingplayerstatechange",a.Xk),a.Xk=null)},VMa=function(a,b,c){a.Yc=c;
a.player.W("presentingplayerstatechange",new g.nH(c,b))},WMa=function(a,b,c){var d=!1;
1===b?d=!a.ut:2===b&&(d=!a.hw);d&&g.pH(c,8)&&(a.player.pauseVideo(),E7(a))},F7=function(a,b){if(b.key!==a.Jl.key)if(b.key===a.Di.key)p7();
else{if(a.tq&&!a.hw&&b!==a.Di&&"cast-selector-receiver"!==b.key&&g.ED(a.player.T()))XMa(a);else{var c;(c=!g.R(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.ut||!a.Bq);(c?0:g.ED(a.player.T())||g.ID(a.player.T()))&&YMa(a)}a.Jl=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.R(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.bb(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.xa,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=dKa(c))&&(a.locationInfo=c)}g7("Connecting to: "+g.Hj(b));"cast-selector-receiver"==b.key?(i7(a||null),b=a||null,
C6()?z6().setLaunchParams(b):x6("setLaunchParams called before ready.")):!a&&s7()&&f7()==b.key?I4("yt-remote-connection-change",!0):(p7(),i7(a||null),a=e7().Ug(),(b=Q4(a,b.key))&&q7(b,1))}},YMa=function(a){a.player.qb().lc()?a.player.pauseVideo():(a.Xk=function(b){WMa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Xk));
a.Bq&&a.Bq.Pc();m7()||(u7=!0)},XMa=function(a){a.player.qb().lc()?a.player.pauseVideo():(a.Xk=function(b){WMa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Xk));
a.tq&&a.tq.Pc();m7()||(u7=!0)},TKa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},q5={"'":"\\'"},ZMa={},mKa={TT:"atp",y3:"ska",q2:"que",A0:"mus",x3:"sus",OX:"dsp",J2:"seq",b0:"mic",OW:"dpa",iU:"cds"},W4,S4="",GKa=BKa("loadCastFramework")||BKa("loadCastApplicationFramework"),IKa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(a5,g.F);g.k=a5.prototype;g.k.xg=function(a){this.B=arguments;this.i=!1;this.yb?this.u=g.Ra()+this.Ff:this.yb=g.Mm(this.C,this.Ff)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.va=function(){this.stop();a5.Gd.va.call(this)};
g.k.NL=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u?(this.yb=g.Mm(this.C,this.u-g.Ra()),this.u=null):this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B))};g.v(b5,g.F);g.k=b5.prototype;g.k.xg=function(a){this.u=arguments;this.yb||this.l?this.i=!0:c5(this)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.yb||(this.i=!1,c5(this))};
g.k.va=function(){g.F.prototype.va.call(this);this.stop()};e5.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
e5.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var g5=new g.bm;g.v(KKa,g.Il);i5.prototype.i=null;i5.prototype.getOptions=function(){var a;(a=this.i)||(a={},MKa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var G7;g.Sa(LKa,i5);G7=new LKa;g.k=j5.prototype;g.k.Tm=null;g.k.Qi=!1;g.k.Rq=null;g.k.LC=null;g.k.Dq=null;g.k.Mq=null;g.k.Cl=null;g.k.Fm=null;g.k.Io=null;g.k.He=null;g.k.ju=0;g.k.Ti=null;g.k.Hx=null;g.k.xl=null;g.k.vr=-1;g.k.VI=!0;g.k.Bn=!1;g.k.Ey=0;g.k.Rw=null;var RKa={},m5={};g.k=j5.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.bS=function(a){a=a.target;var b=this.Rw;b&&3==v5(a)?b.xg():this.LJ(a)};
g.k.LJ=function(a){try{if(a==this.He)a:{var b=v5(this.He),c=this.He.G,d=this.He.getStatus();if(g.ze&&!g.ce(10)||g.Be&&!g.be("420+")){if(4>b)break a}else if(3>b||3==b&&!g.mg&&!x5(this.He))break a;this.Bn||4!=b||7==c||(8==c||0>=d?this.i.Gi(3):this.i.Gi(2));r5(this);var e=this.He.getStatus();this.vr=e;var f=x5(this.He);(this.Qi=200==e)?(4==b&&o5(this),this.G?(SKa(this,b,f),g.mg&&this.Qi&&3==b&&(this.B.Na(this.u,"tick",this.WR),this.u.start())):n5(this,f),this.Qi&&!this.Bn&&(4==b?this.i.Cu(this):(this.Qi=
!1,l5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.xl=3,h5(13)):(this.xl=0,h5(14)),o5(this),p5(this))}}catch(h){this.He&&x5(this.He)}finally{}};
g.k.WR=function(){var a=v5(this.He),b=x5(this.He);this.ju<b.length&&(r5(this),SKa(this,a,b),this.Qi&&4!=a&&l5(this))};
g.k.zR=function(a){f5((0,g.C)(this.yR,this,a),0)};
g.k.yR=function(a){this.Bn||(r5(this),n5(this,a),l5(this))};
g.k.hI=function(a){f5((0,g.C)(this.xR,this,a),0)};
g.k.xR=function(a){this.Bn||(o5(this),this.Qi=a,this.i.Cu(this),this.i.Gi(4))};
g.k.cancel=function(){this.Bn=!0;o5(this)};
g.k.HR=function(){this.Rq=null;var a=Date.now();0<=a-this.LC?(2!=this.Mq&&this.i.Gi(3),o5(this),this.xl=2,h5(18),p5(this)):VKa(this,this.LC-a)};
g.k.getLastError=function(){return this.xl};g.Sa(t5,g.bm);var bLa=/^https?$/i,$Ma=["POST","PUT"];g.k=t5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.V+"; newUri="+a);b=b?b.toUpperCase():"GET";this.V=a;this.u="";this.G=0;this.Fa=b;this.xa=!1;this.B=!0;this.i=this.ra?NKa(this.ra):NKa(G7);this.ma=this.ra?this.ra.getOptions():G7.getOptions();this.i.onreadystatechange=(0,g.C)(this.WH,this);try{H4(w5(this,"Opening Xhr")),this.Ba=!0,this.i.open(b,String(a),!0),this.Ba=!1}catch(f){H4(w5(this,"Error opening Xhr: "+f.message));aLa(this,f);return}a=
c||"";var e=this.headers.clone();d&&iKa(d,function(f,h){e.set(h,f)});
d=g.bb(e.wh(),ZKa);c=g.A.FormData&&a instanceof g.A.FormData;!g.fb($Ma,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Ka&&(this.i.responseType=this.Ka);"withCredentials"in this.i&&this.i.withCredentials!==this.Ea&&(this.i.withCredentials=this.Ea);try{dLa(this),0<this.J&&(this.Y=YKa(this.i),H4(w5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.C)(this.KD,this)):this.X=g.Mm(this.KD,this.J,this)),H4(w5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){H4(w5(this,"Send error: "+f.message)),aLa(this,f)}};
g.k.KD=function(){"undefined"!=typeof g.W_&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.G=8,w5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(w5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.G=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),u5(this))};
g.k.va=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),u5(this,!0));t5.Gd.va.call(this)};
g.k.WH=function(){this.Ga()||(this.Ba||this.L||this.C?cLa(this):this.GQ())};
g.k.GQ=function(){cLa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==v5(this)};
g.k.getStatus=function(){try{return 2<v5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=eLa.prototype;g.k.Fy=null;g.k.Jg=null;g.k.Sw=!1;g.k.fJ=null;g.k.bv=null;g.k.NA=null;g.k.Gy=null;g.k.eb=null;g.k.dk=-1;g.k.wr=null;g.k.Hr=null;g.k.connect=function(a){this.Gy=a;a=y5(this.i,null,this.Gy);h5(3);this.fJ=Date.now();var b=this.i.J;null!=b?(this.wr=b[0],(this.Hr=b[1])?(this.eb=1,fLa(this)):(this.eb=2,A5(this))):(F4(a,"MODE","init"),this.Jg=new j5(this,void 0,void 0,void 0),this.Jg.Tm=this.Fy,k5(this.Jg,a,!1,null,!0),this.eb=0)};
g.k.IM=function(a){if(a)this.eb=2,A5(this);else{h5(4);var b=this.i;b.nj=b.Hl.dk;H5(b,9)}a&&this.Gi(2)};
g.k.Az=function(a){return this.i.Az(a)};
g.k.abort=function(){this.Jg&&(this.Jg.cancel(),this.Jg=null);this.dk=-1};
g.k.LD=function(){return!1};
g.k.ZH=function(a,b){this.dk=a.vr;if(0==this.eb)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.nj=this.dk;H5(a,2);return}this.wr=c[0];this.Hr=c[1]}else a=this.i,a.nj=this.dk,H5(a,2);else if(2==this.eb)if(this.Sw)h5(7),this.NA=Date.now();else if("11111"==b){if(h5(6),this.Sw=!0,this.bv=Date.now(),a=this.bv-this.fJ,!g.ze||g.ce(10)||500>a)this.dk=200,this.Jg.cancel(),h5(12),z5(this.i,this,!0)}else h5(8),this.bv=this.NA=Date.now(),this.Sw=!1};
g.k.Cu=function(){this.dk=this.Jg.vr;if(this.Jg.Qi)0==this.eb?this.Hr?(this.eb=1,fLa(this)):(this.eb=2,A5(this)):2==this.eb&&((!g.ze||g.ce(10)?!this.Sw:200>this.NA-this.bv)?(h5(11),z5(this.i,this,!1)):(h5(12),z5(this.i,this,!0)));else{0==this.eb?h5(9):2==this.eb&&h5(10);var a=this.i;this.Jg.getLastError();a.nj=this.dk;H5(a,2)}};
g.k.Kt=function(){return this.i.Kt()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Gi=function(a){this.i.Gi(a)};g.k=B5.prototype;g.k.mj=null;g.k.Xr=null;g.k.yg=null;g.k.Ud=null;g.k.Hy=null;g.k.ev=null;g.k.ME=null;g.k.Du=null;g.k.Vs=0;g.k.CO=0;g.k.yf=null;g.k.Pl=null;g.k.vk=null;g.k.Jn=null;g.k.Hl=null;g.k.Fx=null;g.k.nq=-1;g.k.GG=-1;g.k.nj=-1;g.k.Up=0;g.k.Jp=0;g.k.Cn=8;g.Sa(hLa,g.Il);g.Sa(iLa,g.Il);g.k=B5.prototype;g.k.connect=function(a,b,c,d,e){h5(0);this.Hy=b;this.Xr=c||{};d&&void 0!==e&&(this.Xr.OSID=d,this.Xr.OAID=e);this.C?(f5((0,g.C)(this.dF,this,a),100),mLa(this)):this.dF(a)};
g.k.dF=function(a){this.Hl=new eLa(this);this.Hl.Fy=this.mj;this.Hl.l=this.B;this.Hl.connect(a)};
g.k.LD=function(){return 0==this.eb};
g.k.getState=function(){return this.eb};
g.k.fI=function(a){this.Pl=null;qLa(this,a)};
g.k.eI=function(){this.vk=null;this.Ud=new j5(this,this.l,"rpc",this.G);this.Ud.Tm=this.mj;this.Ud.Ey=0;var a=this.ME.clone();D4(a,"RID","rpc");D4(a,"SID",this.l);D4(a,"CI",this.Fx?"0":"1");D4(a,"AID",this.nq);C5(this,a);if(!g.ze||g.ce(10))D4(a,"TYPE","xmlhttp"),k5(this.Ud,a,!0,this.Du,!1);else{D4(a,"TYPE","html");var b=this.Ud,c=!!this.Du;b.Mq=3;b.Cl=E4(a.clone());UKa(b,c)}};
g.k.ZH=function(a,b){if(0!=this.eb&&(this.Ud==a||this.yg==a))if(this.nj=a.vr,this.yg==a&&3==this.eb)if(7<this.Cn){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.vk){if(this.Ud)if(this.Ud.Dq+3E3<this.yg.Dq)E5(this),this.Ud.cancel(),this.Ud=null;else break a;G5(this);h5(19)}}else this.GG=a[1],0<this.GG-this.nq&&37500>a[2]&&this.Fx&&0==this.Jp&&!this.Jn&&(this.Jn=f5((0,g.C)(this.eP,this),6E3));else H5(this,11)}else b!=ZMa.DW.i&&H5(this,11);else if(this.Ud==
a&&E5(this),!g.oc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.nq=c[0],c=c[1],2==this.eb?"c"==c[0]?(this.l=c[1],this.Du=c[2],c=c[3],null!=c?this.Cn=c:this.Cn=6,this.eb=3,this.yf&&this.yf.ZE(),this.ME=y5(this,this.Kt()?this.Du:null,this.Hy),rLa(this)):"stop"==c[0]&&H5(this,7):3==this.eb&&("stop"==c[0]?H5(this,7):"noop"!=c[0]&&this.yf&&this.yf.YE(c),this.Jp=0)};
g.k.eP=function(){null!=this.Jn&&(this.Jn=null,this.Ud.cancel(),this.Ud=null,G5(this),h5(20))};
g.k.Cu=function(a){if(this.Ud==a){E5(this);this.Ud=null;var b=2}else if(this.yg==a)this.yg=null,b=1;else return;this.nj=a.vr;if(0!=this.eb)if(a.Qi)1==b?(b=g5,b.dispatchEvent(new hLa(b,a.Io?a.Io.length:0,Date.now()-a.Dq,this.Up)),D5(this),this.u.length=0):rLa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.nj)){if(d=1==b)this.yg||this.Pl||1==this.eb||2<=this.Up?d=!1:(this.Pl=f5((0,g.C)(this.fI,this,a),sLa(this,this.Up)),this.Up++,d=!0);d=!(d||2==b&&G5(this))}if(d)switch(c){case 1:H5(this,
5);break;case 4:H5(this,10);break;case 3:H5(this,6);break;case 7:H5(this,12);break;default:H5(this,2)}}};
g.k.fN=function(a){if(!g.fb(arguments,this.eb))throw Error("Unexpected channel state: "+this.eb);};
g.k.ES=function(a){a?h5(2):(h5(1),tLa(this,8))};
g.k.Az=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new t5;a.Ea=!1;return a};
g.k.isActive=function(){return!!this.yf&&this.yf.isActive(this)};
g.k.Gi=function(a){var b=g5;b.dispatchEvent(new iLa(b,a))};
g.k.Kt=function(){return!(!g.ze||g.ce(10))};
g.k=uLa.prototype;g.k.ZE=function(){};
g.k.YE=function(){};
g.k.XE=function(){};
g.k.kz=function(){};
g.k.GF=function(){return{}};
g.k.isActive=function(){return!0};g.k=vLa.prototype;g.k.isEmpty=function(){return g.gb(this.i)&&g.gb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.fb(this.i,a)||g.fb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.REa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.l,a)};
g.k.Ag=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Sa(I5,g.F);g.k=I5.prototype;g.k.rR=function(){this.Ff=Math.min(3E5,2*this.Ff);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Ff+15E3*Math.random();g.mn(this.i,a);this.l=g.Ra()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Ff=5E3};g.Sa(J5,uLa);g.k=J5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Mf=function(a){return this.u.Mf(a)};
g.k.W=function(a,b){return this.u.W.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.Ci(this.u),yLa(this),g.Ci(this.l),this.l=null,this.Y=function(){return""})};
g.k.Ga=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.V="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ma+"/test";b=this.ma+"/bind";var d=new B5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ra),e=this.i;e&&(e.yf=null);d.yf=this;this.i=d;K5(this);if(this.i){d=g.M("ID_TOKEN");var f=this.i.mj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.mj=f}e?(3!=e.getState()&&0==oLa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.nq)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Wb(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):L5(this)&&(K5(this),nLa(this.i,a))};
g.k.ZE=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)nLa(this.i,a[b])}this.W("handlerOpened")};
g.k.XE=function(a){var b=2==a&&401==this.i.nj;4==a||b||this.l.start();this.W("handlerError",a,b)};
g.k.kz=function(a){if(!this.l.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.GF=function(){var a={v:2};this.V&&(a.gsessionid=this.V);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Wb(a,this.C);return a};
g.k.YE=function(a){"S"==a[0]?this.V=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),lLa(this.i)):this.W("handlerMessage",new wLa(a[0],a[1]))};
g.k.fx=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.xa&&this.i){var b=this.i.mj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.mj=b}};
g.k.lS=function(){this.l.isActive();0==oLa(this.i)&&this.connect(this.C,this.B)};M5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
M5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
M5.prototype.C=function(a){a(Error("request timed out"))};var FLa=Date.now(),P5=null,S5=Array(50),R5=-1,T5=!1;g.Sa(U5,g.O);U5.prototype.Ug=function(){return this.screens};
U5.prototype.contains=function(a){return!!P4(this.screens,a)};
U5.prototype.get=function(a){return a?Q4(this.screens,a):null};
U5.prototype.info=function(a){Q5(this.G,a)};g.v(V5,g.O);g.k=V5.prototype;g.k.start=function(){!this.i&&isNaN(this.yb)&&this.pI()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.yb)||(g.hp(this.yb),this.yb=NaN)};
g.k.va=function(){this.stop();g.O.prototype.va.call(this)};
g.k.pI=function(){this.yb=NaN;this.i=g.mp(N5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.PL,this),onError:(0,g.C)(this.OL,this),onTimeout:(0,g.C)(this.QL,this)})};
g.k.PL=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.G;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.W("pairingComplete",new K4(a),b)};
g.k.OL=function(a){this.i=null;a.status&&404==a.status?this.l>=aNa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=aNa[this.l],this.yb=g.fp((0,g.C)(this.pI,this),a),this.l++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.QL=function(){this.i=null;this.W("pairingFailed",Error("Server not responding"))};
var aNa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(X5,U5);g.k=X5.prototype;g.k.start=function(){W5(this)&&this.W("screenChange");!g.Wu("yt-remote-lounge-token-expiration")&&JLa(this);g.hp(this.i);this.i=g.fp((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){W5(this);GLa(this,a);Y5(this,!1);this.W("screenChange");b(a);a.token||JLa(this)};
g.k.remove=function(a,b){var c=W5(this);ILa(this,a)&&(Y5(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.Dx=function(a,b,c,d){var e=W5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,Y5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.va=function(){g.hp(this.i);X5.Gd.va.call(this)};
g.k.CN=function(a){W5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}Y5(this,!b);b&&Q5(this.G,"Missed "+b+" lounge tokens.")};
g.k.BN=function(a){Q5(this.G,"Requesting lounge tokens failed: "+a)};g.v($5,g.O);g.k=$5.prototype;g.k.start=function(){var a=parseInt(g.Wu("yt-remote-fast-check-period")||"0",10);(this.B=g.Ra()-144E5<a?0:a)?c6(this):(this.B=g.Ra()+3E5,g.Vu("yt-remote-fast-check-period",this.B),this.KB())};
g.k.isEmpty=function(){return g.Pb(this.i)};
g.k.update=function(){Z5("Updating availability on schedule.");var a=this.G(),b=g.Cb(this.i,function(c,d){return c&&!!Q4(a,d)},this);
b6(this,b)};
g.k.va=function(){g.hp(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.O.prototype.va.call(this)};
g.k.KB=function(){g.hp(this.u);this.u=NaN;this.l&&this.l.abort();var a=LLa(this);if(G4(a)){var b=N5(this.C,"/pairing/get_screen_availability");this.l=O5(this.C,b,{lounge_token:g.Kb(a).join(",")},(0,g.C)(this.aR,this,a),(0,g.C)(this.ZQ,this))}else b6(this,{}),c6(this)};
g.k.aR=function(a,b){this.l=null;var c=g.Kb(LLa(this));if(g.xb(c,g.Kb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;b6(this,c);c6(this)}else this.Hd("Changing Screen set during request."),this.KB()};
g.k.ZQ=function(a){this.Hd("Screen availability failed: "+a);this.l=null;c6(this)};
g.k.Hd=function(a){Q5("OnlineScreenService",a)};g.Sa(d6,U5);g.k=d6.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.W("screenChange"),this.i.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Dx=function(a,b,c,d){this.l.contains(a)?this.l.Dx(a,b,c,d):(a="Updating name of unknown screen: "+a.name,Q5(this.G,a),d(Error(a)))};
g.k.Ug=function(a){return a?this.screens:g.nb(this.screens,g.Le(this.u,function(b){return!this.contains(b)},this))};
g.k.MD=function(){return g.Le(this.Ug(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.ND=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new V5(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.Ci(l);e(e6(h,m),n)});
l.subscribe("pairingFailed",function(m){g.Ci(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.RL=function(a,b,c,d){g.mp(N5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){e=new K4(f.screen||{});if(!e.name||PLa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);PLa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(e6(this,e))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.va=function(){g.Ci(this.l);g.Ci(this.i);d6.Gd.va.call(this)};
g.k.IN=function(){RLa(this);this.W("screenChange");this.i.update()};
d6.prototype.dispose=d6.prototype.dispose;g.Sa(g6,g.O);g.k=g6.prototype;g.k.getScreen=function(){return this.B};
g.k.Zf=function(a){this.Ga()||(a&&i6(this,""+a),this.B=null,this.W("sessionScreen",null))};
g.k.info=function(a){Q5(this.xa,a)};
g.k.OD=function(){return null};
g.k.UB=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){i6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.va=function(){this.UB("");g6.Gd.va.call(this)};g.v(j6,g6);g.k=j6.prototype;g.k.TB=function(a){if(this.l){if(this.l==a)return;i6(this,"Overriding cast session with new session object");$La(this);this.ma=!1;this.V="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra);WLa(this,"getMdxSessionStatus")};
g.k.oq=function(a){this.info("launchWithParams no-op for Cast: "+g.Hj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.Zf()},this),(0,g.C)(function(){this.Zf(Error("Failed to stop receiver app."))},this)):this.Zf(Error("Stopping cast device without session."))};
g.k.UB=function(){};
g.k.va=function(){this.info("disposeInternal");$La(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra));this.l=null;g6.prototype.va.call(this)};
g.k.LR=function(a,b){if(!this.Ga())if(b)if(b=d5(b),g.Ma(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Hj(b)),a){case "mdxSessionStatus":ULa(this,b);break;case "loungeToken":XLa(this,b);break;default:i6(this,"Unknown youtube message: "+a)}else i6(this,"Unable to parse message.");else i6(this,"No data in message.")};
g.k.VF=function(a,b,c,d){g.hp(this.L);this.L=0;OLa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(i6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.fp((0,g.C)(this.VF,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.OD=function(){return this.l};
g.k.SL=function(a){this.Ga()||a||(i6(this,"Cast session died."),this.Zf())};g.v(m6,g6);g.k=m6.prototype;g.k.TB=function(a){this.l=a;this.l.addUpdateListener(this.Ba)};
g.k.oq=function(a){this.Ca=a;this.X()};
g.k.stop=function(){gMa(this);this.l?this.l.stop((0,g.C)(this.Zf,this,null),(0,g.C)(this.Zf,this,"Failed to stop DIAL device.")):this.Zf()};
g.k.va=function(){gMa(this);this.l&&this.l.removeUpdateListener(this.Ba);this.l=null;g6.prototype.va.call(this)};
g.k.TL=function(a){this.Ga()||a||(i6(this,"DIAL session died."),this.C(),this.C=g.Ia,this.Zf())};g.v(q6,g6);q6.prototype.stop=function(){this.Zf()};
q6.prototype.TB=function(){};
q6.prototype.oq=function(){g.hp(this.l);this.l=NaN;var a=Q4(this.u.Ug(),this.i.label);a?h6(this,a):this.Zf(Error("No such screen"))};
q6.prototype.va=function(){g.hp(this.l);this.l=NaN;g6.prototype.va.call(this)};g.v(r6,g.O);g.k=r6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.V||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.C)(this.KQ,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.aI,this),e,d,a);c.customDialLaunchCallback=(0,g.C)(this.yP,this);chrome.cast.initialize(c,(0,g.C)(function(){this.Ga()||
(chrome.cast.addReceiverActionListener(this.G),CLa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.PD,this)),this.u=iMa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(f){this.Hd("Failed to set initial custom receivers: "+g.Hj(f))},this)),this.W("yt-remote-cast2-availability-change",t6(this)),b(!0))},this),(0,g.C)(function(f){this.Hd("Failed to initialize API: "+g.Hj(f));
b(!1)},this))};
g.k.qS=function(a,b){s6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)s6("Unsetting old screen status: "+this.i.i.friendlyName),u6(this,null)}if(a&&b){if(!this.i){c=Q4(this.l.Ug(),a);if(!c){s6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){s6("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=hMa(this,c);a||(s6("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(d){this.Hd("Failed to set initial custom receivers: "+g.Hj(d))},this)));
s6("setConnectedScreenStatus: new active receiver: "+a.friendlyName);u6(this,new q6(this.l,a),!0)}this.i.UB(b)}else s6("setConnectedScreenStatus: no screen.")};
g.k.rS=function(a){this.Ga()?this.Hd("Setting connection data on disposed cast v2"):this.i?this.i.oq(a):this.Hd("Setting connection data without a session")};
g.k.VL=function(){this.Ga()?this.Hd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),u6(this,null)):s6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.aI,this),(0,g.C)(this.dR,this))};
g.k.va=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.PD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.G);var a=zLa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Ci(this.i);g.O.prototype.va.call(this)};
g.k.Hd=function(a){Q5("Controller",a)};
g.k.cI=function(a,b){this.i==a&&(b||u6(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.HQ=function(a,b){if(!this.Ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),s6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)s6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{s6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.W("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:u6(this,
new q6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:u6(this,new m6(this.l,a,this.C,this.B));break;case chrome.cast.ReceiverType.CAST:u6(this,new j6(this.l,a,this.B));break;default:this.Hd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Hd("Stopping receiver w/o session: "+a.friendlyName)}else this.Hd("onReceiverAction_ called without receiver.")};
g.k.yP=function(a){if(this.Ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Hd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return s6("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);u6(this,new m6(this.l,b,this.C,this.B))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,n6(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=dMa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.Lo(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=eMa(b,c)):a=eMa(b,c)):a=p6(b);return a};
g.k.aI=function(a){if(!this.Ga()){s6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)s6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),u6(this,new j6(this.l,b,this.B),!0);else{this.Hd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=Q4(this.l.Ug(),c.label);d&&L4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(s6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ci(this.i),this.i=new j6(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.C)(this.cI,this,this.i)),this.i.oq(null));this.i.TB(a)}}};
g.k.UL=function(){return this.i?this.i.OD():null};
g.k.dR=function(a){this.Ga()||(this.Hd("Failed to estabilish a session: "+g.Hj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&u6(this,null))};
g.k.KQ=function(a){s6("Receiver availability updated: "+a);if(!this.Ga()){var b=t6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;t6(this)!=b&&this.W("yt-remote-cast2-availability-change",t6(this))}};
g.k.PD=function(){this.Ga()||(this.u=iMa(this),s6("Updating custom receivers: "+g.Hj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(){this.Hd("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",t6(this)))};
r6.prototype.setLaunchParams=r6.prototype.rS;r6.prototype.setConnectedScreenStatus=r6.prototype.qS;r6.prototype.stopSession=r6.prototype.VL;r6.prototype.getCastSession=r6.prototype.UL;r6.prototype.requestSession=r6.prototype.requestSession;r6.prototype.init=r6.prototype.init;r6.prototype.dispose=r6.prototype.dispose;var A6=[];g.k=F6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";G6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Cj=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.G=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.L=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.lc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.l?this.C+H6(this):this.C};
g.k.clone=function(){return new F6(L6(this))};g.v(N6,g.O);g.k=N6.prototype;g.k.getState=function(){return this.eb};
g.k.play=function(){P6(this)?(this.i?this.i.play(null,g.Ia,U6(this,"play")):T6(this,"play"),S6(this,1,J6(O6(this))),this.W("remotePlayerChange")):Q6(this,this.play)};
g.k.pause=function(){P6(this)?(this.i?this.i.pause(null,g.Ia,U6(this,"pause")):T6(this,"pause"),S6(this,2,J6(O6(this))),this.W("remotePlayerChange")):Q6(this,this.pause)};
g.k.seekTo=function(a){if(P6(this)){if(this.i){var b=O6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.lc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,U6(this,"seekTo",{newTime:a}))}else T6(this,"seekTo",{newTime:a});S6(this,3,a);this.W("remotePlayerChange")}else Q6(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(P6(this)){this.i?this.i.stop(null,g.Ia,U6(this,"stopVideo")):T6(this,"stopVideo");var a=O6(this);a.index=-1;a.videoId="";G6(a);R6(this,a);this.W("remotePlayerChange")}else Q6(this,this.stop)};
g.k.setVolume=function(a,b){if(P6(this)){var c=O6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){Q5("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Hd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){Q5("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Hd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);T6(this,"setVolume",e)}c.muted=b;c.volume=a;R6(this,c)}else Q6(this,g.Pa(this.setVolume,a,b))};
g.k.QD=function(a,b){if(P6(this)){var c=O6(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Hj(b.style),g.Wb(a,c.trackData));T6(this,"setSubtitlesTrack",a);R6(this,c)}else Q6(this,g.Pa(this.QD,a,b))};
g.k.setAudioTrack=function(a,b){P6(this)?(b=b.getLanguageInfo().getId(),T6(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=O6(this),a.audioTrackId=b,R6(this,a)):Q6(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=O6(this);c=c||0;var m={videoId:a,currentIndex:c};K6(l,a,c);void 0!==b&&(I6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Hj(h));T6(this,"setPlaylist",m);d||R6(this,l)};
g.k.Nw=function(a,b){if(P6(this)){if(a&&b){var c=O6(this);K6(c,a,b);R6(this,c)}T6(this,"previous")}else Q6(this,g.Pa(this.Nw,a,b))};
g.k.nextVideo=function(a,b){if(P6(this)){if(a&&b){var c=O6(this);K6(c,a,b);R6(this,c)}T6(this,"next")}else Q6(this,g.Pa(this.nextVideo,a,b))};
g.k.qF=function(){P6(this)?T6(this,"dismissAutoplay"):Q6(this,this.qF)};
g.k.dispose=function(){if(3!=this.eb){var a=this.eb;this.eb=3;this.W("proxyStateChange",a,this.eb)}g.O.prototype.dispose.call(this)};
g.k.va=function(){uMa(this);this.u=null;this.B.clear();M6(this,null);g.O.prototype.va.call(this)};
g.k.WB=function(a){if((a!=this.eb||2==a)&&3!=this.eb&&0!=a){var b=this.eb;this.eb=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.gb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.EQ=function(a,b){this.W(a,b)};
g.k.kP=function(a){if(!a)this.Ys(null),M6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=O6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Q5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,R6(this,b)}};
g.k.Ys=function(a){Q5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),vMa(this),this.W("remotePlayerChange")};
g.k.jP=function(a){a?(vMa(this),this.W("remotePlayerChange")):this.Ys(null)};
g.k.pC=function(){T6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.rP=function(){var a=rMa();a&&M6(this,a)};
g.k.Hd=function(a){Q5("CP",a)};g.v(V6,g.O);g.k=V6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime;b=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);b&&(l.locationInfo=b);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.ac.listId=c);this.ac.videoId=d;this.ac.index=h||0;this.ac.state=3;I6(this.ac,m);this.B="UNSUPPORTED";W6("Connecting with setPlaylist and params: "+g.Hj(l));this.i.connect({method:"setPlaylist",
params:g.Hj(l)},a,uKa())}else W6("Connecting without params"),this.i.connect({},a,uKa());xMa(this)};
g.k.fx=function(a){this.i.fx(a)};
g.k.dispose=function(){this.Ga()||(this.W("beforeDispose"),X6(this,3));g.O.prototype.dispose.call(this)};
g.k.va=function(){Y6(this);$6(this);Z6(this);g.hp(this.J);this.J=NaN;g.hp(this.L);this.L=NaN;this.u=null;g.Mp(this.V);this.V.length=0;this.i.dispose();g.O.prototype.va.call(this);this.B=this.G=this.l=this.ac=this.i=null};
g.k.yN=function(){this.Qp(2)};
g.k.oP=function(){W6("Channel opened");this.ma&&(this.ma=!1,Z6(this),this.Y=g.fp((0,g.C)(function(){W6("Timing out waiting for a screen.");this.Qp(1)},this),15E3));
yKa(xLa(this.i),this.Ba)};
g.k.lP=function(){W6("Channel closed");isNaN(this.C)?V4(!0):V4();this.dispose()};
g.k.mP=function(a,b){V4();isNaN(this.As())?(b&&"shortLived"==this.ra&&this.W("browserChannelAuthError",a),W6("Channel error: "+a+" without reconnection"),this.dispose()):(this.ma=!0,W6("Channel error: "+a+" with reconnection in "+this.As()+" ms"),X6(this,2))};
g.k.nP=function(a){a.params?W6("Received: action="+a.action+", params="+g.Hj(a.params)):W6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=d5(a.params.devices);this.l=g.Nc(a,function(c){return new J4(c)});
a=!!g.bb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
AMa(this,a);break;case "loungeScreenDisconnected":g.lb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
AMa(this,!1);break;case "remoteConnected":var b=new J4(d5(a.params.device));g.bb(this.l,function(c){return b?c.id==b.id:!1})||eKa(this.l,b);
break;case "remoteDisconnected":b=new J4(d5(a.params.device));g.lb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":CMa(this,a);break;case "nowPlaying":EMa(this,a);break;case "onStateChange":DMa(this,a);break;case "onAdStateChange":FMa(this,a);break;case "onVolumeChanged":GMa(this,a);break;case "onSubtitlesTrackChanged":BMa(this,a);break;case "nowAutoplaying":HMa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.W("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.W("autoplayModeChange",this.B);"DISABLED"==this.B&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":IMa(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;default:W6("Unrecognized action: "+a.action)}};
g.k.hS=function(){if(this.u){var a=this.u;this.u=null;this.ac.videoId!=a&&a7(this,"getNowPlaying")}};
g.k.tN=function(){var a=3;this.Ga()||(a=0,isNaN(this.As())?L5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Qp=function(a){W6("Disconnecting with "+a);Y6(this);this.W("beforeDisconnect",a);1==a&&V4();yLa(this.i,a);this.dispose()};
g.k.rN=function(){var a=this.ac;this.u&&(a=this.ac.clone(),K6(a,this.u,a.index));return L6(a)};
g.k.sS=function(a){var b=new F6(a);b.videoId&&b.videoId!=this.ac.videoId&&(this.u=b.videoId,g.hp(this.J),this.J=g.fp((0,g.C)(this.hS,this),5E3));var c=[];this.ac.listId==b.listId&&this.ac.videoId==b.videoId&&this.ac.index==b.index||c.push("remoteQueueChange");this.ac.playerState==b.playerState&&this.ac.volume==b.volume&&this.ac.muted==b.muted&&J6(this.ac)==J6(b)&&g.Hj(this.ac.trackData)==g.Hj(b.trackData)||c.push("remotePlayerChange");this.ac.reset(a);g.zb(c,function(d){this.W(d)},this)};
g.k.UF=function(){var a=this.i.G.id,b=g.bb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.As=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Ra():NaN};
g.k.pN=function(){return this.B||"UNSUPPORTED"};
g.k.qN=function(){return this.G||""};
g.k.WL=function(){if(!isNaN(this.As())){var a=this.i.l;a.i.xg();a.start()}};
g.k.pS=function(a,b){a7(this,a,b);zMa(this)};
g.k.RD=function(){var a=g.wo("SID","")||"",b=g.wo("SAPISID","")||"",c=g.wo("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.rf(g.Ve(a),2);b=g.rf(g.Ve(b),2);c=g.rf(g.Ve(c),2);return g.rf(g.Ve(a+","+b+","+c),2)};
V6.prototype.subscribe=V6.prototype.subscribe;V6.prototype.unsubscribeByKey=V6.prototype.Mf;V6.prototype.getProxyState=V6.prototype.tN;V6.prototype.disconnect=V6.prototype.Qp;V6.prototype.getPlayerContextData=V6.prototype.rN;V6.prototype.setPlayerContextData=V6.prototype.sS;V6.prototype.getOtherConnectedRemoteId=V6.prototype.UF;V6.prototype.getReconnectTimeout=V6.prototype.As;V6.prototype.getAutoplayMode=V6.prototype.pN;V6.prototype.getAutoplayVideoId=V6.prototype.qN;V6.prototype.reconnect=V6.prototype.WL;
V6.prototype.sendMessage=V6.prototype.pS;V6.prototype.getXsrfToken=V6.prototype.RD;g.v(b7,U5);g.k=b7.prototype;g.k.Ug=function(a){return this.Ef.$_gs(a)};
g.k.contains=function(a){return!!this.Ef.$_c(a)};
g.k.get=function(a){return this.Ef.$_g(a)};
g.k.start=function(){this.Ef.$_st()};
g.k.add=function(a,b,c){this.Ef.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ef.$_r(a,b,c)};
g.k.Dx=function(a,b,c,d){this.Ef.$_un(a,b,c,d)};
g.k.va=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ef.$_ubk(this.i[a]);this.i.length=0;this.Ef=null;U5.prototype.va.call(this)};
g.k.XL=function(){this.W("screenChange")};
g.k.lQ=function(){this.W("onlineScreenChange")};
d6.prototype.$_st=d6.prototype.start;d6.prototype.$_gspc=d6.prototype.RL;d6.prototype.$_gsppc=d6.prototype.ND;d6.prototype.$_c=d6.prototype.contains;d6.prototype.$_g=d6.prototype.get;d6.prototype.$_a=d6.prototype.add;d6.prototype.$_un=d6.prototype.Dx;d6.prototype.$_r=d6.prototype.remove;d6.prototype.$_gs=d6.prototype.Ug;d6.prototype.$_gos=d6.prototype.MD;d6.prototype.$_s=d6.prototype.subscribe;d6.prototype.$_ubk=d6.prototype.Mf;var o7=null,u7=!1,c7=null,d7=null,t7=null,h7=[];g.v(v7,g.F);g.k=v7.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.Pb;a.unsubscribe("proxyStateChange",this.YH,this);a.unsubscribe("remotePlayerChange",this.kt,this);a.unsubscribe("remoteQueueChange",this.Jw,this);a.unsubscribe("previousNextChange",this.VH,this);a.unsubscribe("nowAutoplaying",this.PH,this);a.unsubscribe("autoplayDismissed",this.mH,this);this.Pb=this.l=null};
g.k.SD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Pb.eb)if(w7(this)){if(!O6(this.Pb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":O6(this.Pb).lc()?this.Pb.pause():this.Pb.play();break;case "control_play":this.Pb.play();break;case "control_pause":this.Pb.pause();break;case "control_seek":this.J.xg(c[0],c[1]);break;case "control_subtitles_set_track":x7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();y7(this,0===c?void 0:c);break;case "control_seek":y7(this,c[0]);break;case "control_subtitles_set_track":x7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.hP=function(a){this.L.xg(a)};
g.k.WS=function(a){this.SD("control_subtitles_set_track",g.Pb(a)?null:a)};
g.k.jJ=function(){var a=this.I.getOption("captions","track");g.Pb(a)||x7(this,a)};
g.k.Tb=function(a){this.l.Tb(a,this.I.getVideoData().lengthSeconds)};
g.k.UP=function(){g.Pb(this.B)||TMa(this,this.B);this.C=!1};
g.k.YH=function(a,b){this.u.stop();2===b&&this.eJ()};
g.k.kt=function(){if(w7(this)){this.i.stop();var a=O6(this.Pb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Oe=1;break;case 1082:case 1083:this.l.Oe=0;break;default:this.l.Oe=-1}switch(a.playerState){case 1081:case 1:this.Hb(new g.YI(8));this.dJ();break;case 1085:case 3:this.Hb(new g.YI(9));break;case 1083:case 0:this.Hb(new g.YI(2));this.J.stop();this.Tb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Hb(new g.YI(4));break;case 2:this.Hb(new g.YI(4));this.Tb(J6(a));
break;case -1:this.Hb(new g.YI(64));break;case -1E3:this.Hb(new g.YI(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=O6(this.Pb).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,TMa(this,a));a=O6(this.Pb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.V.isActive()||this.EJ()}else SMa(this)};
g.k.VH=function(){this.I.W("mdxpreviousnextchange")};
g.k.Jw=function(){w7(this)||SMa(this)};
g.k.PH=function(a){isNaN(a)||this.I.W("mdxnowautoplaying",a)};
g.k.mH=function(){this.I.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){w7(this)&&this.Pb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===O6(this.Pb).playerState?y7(this,a):b&&this.Pb.seekTo(a)};
g.k.EJ=function(){var a=this;if(w7(this)){var b=O6(this.Pb);this.events.dc(this.X);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.X=this.events.N(this.I,"onVolumeChange",function(c){RMa(a,c)})}};
g.k.dJ=function(){this.i.stop();if(!this.Pb.Ga()){var a=O6(this.Pb);a.lc()&&this.Hb(new g.YI(8));this.Tb(J6(a));this.i.start()}};
g.k.eJ=function(){this.u.stop();this.i.stop();var a=this.Pb.u.getReconnectTimeout();2==this.Pb.eb&&!isNaN(a)&&this.u.start()};
g.k.Hb=function(a){this.u.stop();var b=this.G;if(!g.cJ(b,a)){var c=g.U(a,2);c!==g.U(this.G,2)&&this.I.Mo(c);this.G=a;VMa(this.l,b,a)}};g.v(z7,g.V);z7.prototype.Pc=function(){this.i.show()};
z7.prototype.Ab=function(){this.i.hide()};
z7.prototype.l=function(){g.EI("https://support.google.com/youtube/answer/7640706")};
z7.prototype.u=function(){I4("mdx-manual-pairing-popup-ok");this.Ab()};g.v(A7,g.V);A7.prototype.Pc=function(){this.i.show()};
A7.prototype.Ab=function(){this.i.hide()};
A7.prototype.l=function(){I4("mdx-privacy-popup-cancel");this.Ab()};
A7.prototype.u=function(){I4("mdx-privacy-popup-confirm");this.Ab()};g.v(B7,g.V);B7.prototype.l=function(a){UMa(this,a.state)};g.v(C7,g.OO);C7.prototype.C=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.Cm=g.Ab(a,this.i,this),g.PO(this,g.Nc(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.jh(a),this.enable(!0)):this.enable(!1)};
C7.prototype.i=function(a){return a.key};
C7.prototype.di=function(a){return"cast-selector-receiver"===a?"Cast...":this.Cm[a].name};
C7.prototype.We=function(a){g.OO.prototype.We.call(this,a);this.I.setOption("remote","currentReceiver",this.Cm[a]);this.wb.Ab()};g.v(D7,g.cM);g.k=D7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.gD(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.R(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.R(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.R(a.experiments,"enable_cast_short_lived_lounge_token")};MMa(b,a);this.subscriptions.push(g.Kq("yt-remote-before-disconnect",this.gP,this));this.subscriptions.push(g.Kq("yt-remote-connection-change",this.LQ,this));this.subscriptions.push(g.Kq("yt-remote-receiver-availability-change",
this.XH,this));this.subscriptions.push(g.Kq("yt-remote-auto-connect",this.JQ,this));this.subscriptions.push(g.Kq("yt-remote-receiver-resumed",this.IQ,this));this.subscriptions.push(g.Kq("mdx-privacy-popup-confirm",this.ZR,this));this.subscriptions.push(g.Kq("mdx-privacy-popup-cancel",this.YR,this));this.subscriptions.push(g.Kq("mdx-manual-pairing-popup-ok",this.rO,this));this.XH()};
g.k.load=function(){this.player.cancelPlayback();g.cM.prototype.load.call(this);this.nh=new v7(this,this.player,this.Pb);var a=(a=QMa())?a.currentTime:0;var b=s7()?new N6(m7(),void 0):null;0==a&&b&&(a=J6(O6(b)));0!==a&&this.Tb(a);VMa(this,this.Yc,this.Yc);this.player.Sj(6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.Jl=this.Di;g.Di(this.nh,this.Pb);this.Pb=this.nh=null;g.cM.prototype.unload.call(this);this.player.Sj(5);E7(this)};
g.k.va=function(){g.Lq(this.subscriptions);g.cM.prototype.va.call(this)};
g.k.Nj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.nh.SD.apply(this.nh,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.Oe};
g.k.uN=function(){return this.loaded?this.nh.suggestion:null};
g.k.Cj=function(){return this.Pb?O6(this.Pb).Cj:!1};
g.k.hasNext=function(){return this.Pb?O6(this.Pb).hasNext:!1};
g.k.Tb=function(a,b){this.HG=a||0;this.player.W("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.HG};
g.k.getProgressState=function(){var a=O6(this.Pb),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Ne():!a.isAdPlaying()&&this.player.Ne(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+H6(a):a.u,isAtLiveHead:1>=(a.l?a.i+H6(a):a.i)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.l?a.i+H6(a):a.i,seekableStart:0<a.B?a.B+
H6(a):a.B}};
g.k.nextVideo=function(){this.Pb&&this.Pb.nextVideo()};
g.k.Nw=function(){this.Pb&&this.Pb.Nw()};
g.k.gP=function(a){1===a&&(this.yB=this.Pb?O6(this.Pb):null)};
g.k.LQ=function(){var a=s7()?new N6(m7(),void 0):null;if(a){var b=this.Jl;this.loaded&&this.unload();this.Pb=a;this.yB=null;b.key!==this.Di.key&&(this.Jl=b,this.load())}else g.Ci(this.Pb),this.Pb=null,this.loaded&&(this.unload(),(a=this.yB)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,J6(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.XH=function(){var a=[this.Di],b=a.concat,c=NMa();B6()&&g.Wu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Cm=b.call(a,c);a=n7()||this.Di;F7(this,a);this.player.La("onMdxReceiversChange")};
g.k.JQ=function(){var a=n7();F7(this,a)};
g.k.IQ=function(){this.Jl=n7()};
g.k.ZR=function(){this.ut=!0;E7(this);u7=!1;o7&&q7(o7,1);o7=null};
g.k.YR=function(){this.ut=!1;E7(this);F7(this,this.Di);this.Jl=this.Di;u7=!1;o7=null;this.player.playVideo()};
g.k.rO=function(){this.hw=!0;E7(this);g.Vu("yt-remote-manual-pairing-warning-shown",!0,2592E3);u7=!1;o7&&q7(o7,1);o7=null};
g.k.Je=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Cm;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?D6():F7(this,b)),this.loaded?this.Jl:this.Di;case "quickCast":return 2===this.Cm.length&&"cast-selector-receiver"===this.Cm[1].key?(b&&D6(),!0):!1}};
g.k.pC=function(){this.Pb.pC()};
g.k.Sh=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.iM.remote=D7;})(_yt_player);
